version: "3.7"
services:
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
        - db-password
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--password=$$MYSQL_PASSWORD", "--silent"]
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy

  proxy:
    build: proxy
    restart: always
    ports:
      - 85:85
    depends_on:
      - backend
    networks:
      - frontnet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
