steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:latest', './backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/proxy:latest', './proxy']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/proxy:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', 'secret', 'generic', 'db-password', '--from-file=db/password.txt']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=YOUR_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=YOUR_CLUSTER_NAME'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=YOUR_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=YOUR_CLUSTER_NAME'
images:
- 'gcr.io/$PROJECT_ID/backend:latest'
- 'gcr.io/$PROJECT_ID/proxy:latest'